# Generated by Django 4.2.27 on 2025-12-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Your full address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about your services', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, help_text='Your date of birth', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, help_text='City where you provide services', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kvk_number',
            field=models.CharField(blank=True, help_text='KVK (Chamber of Commerce) number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='service_type',
            field=models.CharField(blank=True, help_text='What kind of service do you provide?', max_length=200, null=True),
        ),
    ]
