# Generated by Django 4.2.27 on 2025-12-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_address_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('provider', 'Service Provider'), ('superadmin', 'Super Administrator')], max_length=10),
        ),
    ]
