# Generated by Django 4.2.27 on 2025-12-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('provider', 'Service Provider'), ('superadmin', 'Super Administrator')], max_length=20),
        ),
    ]
