# Generated by Django 4.2.27 on 2025-12-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('plumbing', 'Plumbing'), ('salon', 'Salon & Beauty'), ('therapy', 'Therapy'), ('cleaning', 'Cleaning'), ('tutoring', 'Tutoring'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(choices=[('amsterdam', 'Amsterdam'), ('rotterdam', 'Rotterdam'), ('utrecht', 'Utrecht'), ('den_haag', 'Den Haag')], max_length=50)),
                ('rating', models.FloatField(default=0.0)),
                ('years_experience', models.IntegerField(default=0)),
                ('completed_jobs', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
