# Generated by Django 4.2.27 on 2025-12-26 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Hair Styling, Math Tutoring', max_length=200)),
                ('category', models.CharField(choices=[('salon_beauty', 'Salon & Beauty'), ('health_wellness', 'Health & Wellness'), ('education', 'Education & Tutoring'), ('home_services', 'Home Services'), ('fitness', 'Fitness & Sports'), ('technology', 'Technology & IT'), ('business', 'Business & Consulting'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Describe what this service includes')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in EUR', max_digits=10)),
                ('duration', models.IntegerField(choices=[(30, '30 minutes'), (60, '1 hour'), (90, '1.5 hours'), (120, '2 hours'), (180, '3 hours'), (240, '4 hours')], default=60, help_text='Service duration')),
                ('is_active', models.BooleanField(default=True, help_text='Is this service currently offered?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created_at'],
            },
        ),
    ]
