# Generated by Django 4.2.27 on 2025-12-26 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'start_time'], 'verbose_name_plural': 'Availabilities'},
        ),
        migrations.AddField(
            model_name='availability',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Which service is available during this time', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='bookings.service'),
        ),
    ]
