# Generated by Django 6.0 on 2025-12-27 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_custome_10bd54_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_provide_7ad8bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_date_c2c738_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='availability',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='bookings.availability'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='provider_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
