# Generated by Django 6.0 on 2025-12-27 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='availability',
            field=models.OneToOneField(help_text='Booked availability slot', on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='bookings.availability'),
        ),
    ]
