# Generated by Django 4.2.27 on 2025-12-29 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0009_alter_booking_availability'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provider',
            new_name='OldProvider',
        ),
        migrations.AlterModelOptions(
            name='oldprovider',
            options={'verbose_name': 'Old Provider (Deprecated)', 'verbose_name_plural': 'Old Providers (Deprecated)'},
        ),
        migrations.AlterModelTable(
            name='oldprovider',
            table='bookings_provider',
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, help_text='Business or trading name', max_length=200, null=True)),
                ('kvk_number', models.CharField(blank=True, help_text='KVK (Chamber of Commerce) number', max_length=20, null=True)),
                ('service_type', models.CharField(choices=[('salon_beauty', 'Salon & Beauty'), ('health_wellness', 'Health & Wellness'), ('education', 'Education & Tutoring'), ('home_services', 'Home Services'), ('fitness', 'Fitness & Sports'), ('technology', 'Technology & IT'), ('business', 'Business & Consulting'), ('other', 'Other')], help_text='Primary service category', max_length=50)),
                ('bio', models.TextField(help_text='About the provider and their services')),
                ('city', models.CharField(help_text='City where services are provided', max_length=100)),
                ('address', models.CharField(blank=True, help_text='Full address (optional)', max_length=255, null=True)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=20)),
                ('website', models.URLField(blank=True, help_text='Website URL (optional)', null=True)),
                ('years_experience', models.IntegerField(default=0, help_text='Years of professional experience')),
                ('rating', models.FloatField(default=0.0, help_text='Average rating (0-5)')),
                ('total_bookings', models.IntegerField(default=0, help_text='Total number of completed bookings')),
                ('is_verified', models.BooleanField(default=False, help_text='Has the provider been verified?')),
                ('is_active', models.BooleanField(default=True, help_text='Is the provider currently accepting bookings?')),
                ('profile_image', models.URLField(blank=True, help_text='Profile image URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User account for this provider', on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Profile',
                'verbose_name_plural': 'Provider Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
