# Generated by Django 4.2.27 on 2025-12-29 18:17

from django.db import migrations


def populate_provider_profiles(apps, schema_editor):
    """
    Populate ProviderProfile table with data from UserProfile where user_type='provider'
    """
    UserProfile = apps.get_model('accounts', 'UserProfile')
    ProviderProfile = apps.get_model('bookings', 'ProviderProfile')

    # Get all providers from UserProfile
    providers = UserProfile.objects.filter(user_type='provider')

    created_count = 0
    for user_profile in providers:
        # Check if ProviderProfile already exists for this user
        if not ProviderProfile.objects.filter(user=user_profile.user).exists():
            # Create ProviderProfile from UserProfile data
            ProviderProfile.objects.create(
                user=user_profile.user,
                service_type=user_profile.service_type or 'other',  # Default to 'other' if empty
                bio=user_profile.bio or f"Services provided by {user_profile.user.username}",  # Default bio
                city=user_profile.city or 'Not specified',  # Default city
                phone_number=user_profile.phone_number or '',
                kvk_number=user_profile.kvk_number or '',
                # Default values for new fields
                years_experience=0,
                rating=0.0,
                total_bookings=0,
                is_verified=False,
                is_active=True,
            )
            created_count += 1

    print(f"✓ Created {created_count} ProviderProfile records from UserProfile")


def reverse_migration(apps, schema_editor):
    """
    Reverse: Delete all ProviderProfile records
    """
    ProviderProfile = apps.get_model('bookings', 'ProviderProfile')
    count = ProviderProfile.objects.count()
    ProviderProfile.objects.all().delete()
    print(f"✓ Deleted {count} ProviderProfile records")


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_rename_provider_add_providerprofile'),
        ('accounts', '__latest__'),  # Ensure accounts migrations have run
    ]

    operations = [
        migrations.RunPython(populate_provider_profiles, reverse_migration),
    ]
